channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=25.1.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==5.9.6
  - scipy==1.11.4
  - statsmodels==0.14.1
name: mlflow-env
